'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'
import { checkIsPublicRoute } from '@/functions/check-is-public-route'
import PrivateRoute from '@/components/PrivateRoute'
import { useContext } from 'react'
import { AppProvider } from '@/contexts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Novo Gestor Jurídico',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathName = usePathname()
  const isPublicPage = checkIsPublicRoute(pathName!)

  console.log(isPublicPage)

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          {isPublicPage && children}

          {!isPublicPage && <PrivateRoute> {children} </PrivateRoute>}
        </AppProvider>
      </body>
    </html>
  )
}
